version: "3"
services:
  nuxt.dnlrns.dev:
    image: "node:8-jessie"
    working_dir: /home/node/app
    expose:
      - 3000
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    labels:
      - "traefik.enable=true"
      - "traefik.backend=nuxt.dnlrns.dev"
      - "traefik.fronted.rule=Host:dnlnrs.dev"
      - "traefik.passHostHeader=true"
      - "traefik.docker.network=web"
    command: /bin/sh -c "yarn install && yarn build && yarn start"
    networks:
      - web

networks:
  web:
    external: true
